apiVersion: v1
kind: Service
metadata:
  name: guacamole
spec:
  ports:
  - name: default
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: guacamole
  sessionAffinity: None
  type: ClusterIP
