apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: guacamole
  name: guacamole
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: guacamole
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: guacamole
    spec:
      containers:
      - name: guacamole
        image: ghcr.io/jmcarbo/guacamole:v1.3.0
        imagePullPolicy: Always
        env:      
        - name: TZ
          value: CET
        - name: POSTGRES_DATABASE
          value: guacamole
        - name: POSTGRES_USER
          value: guacamole
        - name: POSTGRES_HOSTNAME
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_PASSWORD
          value: VeptOmriga
        - name: GUACD_HOSTNAME
          value: guacamole-server
        - name: GUACD_PORT
          value: "4822"
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
